spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://127.0.0.1:3306/sys?characterEncoding=utf-8&useSSL=false&autoReconnect=true
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
  batch:
    job:
      enabled: false